spring:
  rabbitmq:
    addresses: amqps://ovuuxdgy:VnHmKmLYq_8Y7QY0HIr8D2ySQfZdOrgI@jellyfish.rmq.cloudamqp.com/ovuuxdgy
  cloud:
    stream:
      bindings:
        orderChannel:
          destination: loan.order
        statusChannel:
          destination: loan.result
          group: status
server:
  port: 8080
