spring:
  rabbitmq:
    addresses: amqps://ovuuxdgy:VnHmKmLYq_8Y7QY0HIr8D2ySQfZdOrgI@jellyfish.rmq.cloudamqp.com/ovuuxdgy
  cloud:
    stream:
      bindings:
        orderChannel:
          destination: loan.order
          group: pending
        approved:
          destination: loan.checker
        declined:
          destination: loan.checker
        statusChannel:
          destination: loan.result
      rabbit:
        bindings:
          approved:
            producer:
              exchangeType: topic
              routingKeyExpression: '"approved"'
          declined:
            producer:
              exchangeType: topic
              routingKeyExpression: '"declined"'
server:
  port: 9090
